name: Install NVHPC

on: [push]

jobs:
  install-nvhpc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download NVHPC
        run: |
          wget -nv https://developer.download.nvidia.com/hpc-sdk/23.9/nvhpc_2023_239_Linux_x86_64_cuda_multi.tar.gz
          echo "Downloaded NVHPC."

      - name: Extract NVHPC
        run: |   
          tar -xzf nvhpc_2023_239_Linux_x86_64_cuda_multi.tar.gz
          echo "Extracted NVHPC."

      - name: Install NVHPC
        run:  |
          nvhpc_2023_239_Linux_x86_64_cuda_multi/install
          echo "Installed NVHPC."
