name: Install NVHPC

on: [push]

jobs:
  install-nvhpc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: somecheck
        run: |
          du -h --max-depth=1 . | sort -h
          ls -a /opt
          du -h --max-depth=1 /opt | sort -h
          ls -a /
          ls -a /mnt
          du -h --max-depth=1 /opt | sort -h
          df -h
      
      - name: Curl 
        run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-23-9

      - name: Check install
        run: |
          echo "Checking NVHPC installation"
          which nvcc
          nvcc -V
          which nvc
          nvc -V
          which nvc++
          nvc++ -V
          echo $LD_LIBRARY_PATH
          echo $PATH
