name: Install NVHPC

on: [push]

jobs:
  install-nvhpc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: somecheck
        run: |
          du -h --max-depth=1 . | sort -h
          ls -a /opt
          du -h --max-depth=1 /opt | sort -h

      - name: Download and install NVHPC
        run: |
          wget -nv https://developer.download.nvidia.com/hpc-sdk/23.9/nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
          echo "Downloaded NVHPC."
          tar xpzf nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
          echo "Extracted NVHPC."
          nvhpc_2023_239_Linux_x86_64_cuda_12.2/install
          echo "Installed NVHPC."
          echo "NVHPC installation complete."
