name: Install NVHPC

on: [push]

jobs:
  install-nvhpc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: somecheck
        run: |
          du -h --max-depth=1 . | sort -h
          ls -a /opt
          du -h --max-depth=1 /opt | sort -h
          ls -a /
          ls -a /mnt
          du -h --max-depth=1 /opt | sort -h
          df -h
      
      - name: Curl 
        run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-23-9

      - name: Download and install NVHPC
        run: |
          echo "Downloading NVHPC...."
          wget -nv https://developer.download.nvidia.com/hpc-sdk/23.9/nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
          echo "Downloaded NVHPC."
          echo "Extracting NVHPC...."
          tar xpzf nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
          echo "Extracted NVHPC."
          rm -rf nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
          echo "Installing NVHPC...."
          nvhpc_2023_239_Linux_x86_64_cuda_12.2/install
          echo "Installed NVHPC."
          echo "NVHPC installation complete."
